import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ClerkProvider } from "@clerk/nextjs";
import { Layout, Main } from "@/ui-core";
import { CartProvider, WatchlistProvider } from "@/context";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const quicksand = Quicksand({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-quicksand",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={quicksand.variable}>
				<QueryClientProvider client={queryClient}>
					<ClerkProvider>
						<WatchlistProvider>
							<CartProvider>
								<Layout>
									<Main>{children}</Main>
								</Layout>
							</CartProvider>
						</WatchlistProvider>
					</ClerkProvider>
					<ReactQueryDevtools initialIsOpen={false} />
				</QueryClientProvider>
			</body>
		</html>
	);
}
